"""empty message

Revision ID: 278ab01af635
Revises: a3ee56f26efc
Create Date: 2022-06-12 01:26:23.266627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278ab01af635'
down_revision = 'a3ee56f26efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_thread',
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('child_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['post.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_thread')
    op.drop_table('post')
    # ### end Alembic commands ###
